// Local logos for protocols and chains (served from /logos/)
export const PROTOCOL_LOGOS: Record<string, string> = {
  aave: '/logos/protocols/aave.svg',
  euler: '/logos/protocols/euler.svg',
  fluid: '/logos/protocols/fluid.svg',
  jito: '/logos/protocols/jito.svg',
  jupiter: '/logos/protocols/jupiter.svg',
  justlend: '/logos/protocols/justlend.svg',
  kamino: '/logos/protocols/kamino.svg',
  lido: '/logos/protocols/lido.svg',
  marinade: '/logos/protocols/marinade.svg',
  morpho: '/logos/protocols/morpho.svg',
  pendle: '/logos/protocols/pendle.svg',
  raydium: '/logos/protocols/raydium.svg',
  rocketpool: '/logos/protocols/rocketpool.svg',
  sparklend: '/logos/protocols/sparklend.svg',
  uniswap: '/logos/protocols/uniswap.svg',
};

export const CHAIN_LOGOS: Record<string, string> = {
  aptos: '/logos/chains/aptos.png',
  arbitrum: '/logos/chains/arbitrum.png',
  avalanche: '/logos/chains/avalanche.png',
  base: '/logos/chains/base.png',
  bitcoin: '/logos/chains/bitcoin.png',
  blast: '/logos/chains/blast.png',
  bsc: '/logos/chains/bsc.png',
  celo: '/logos/chains/celo.png',
  ethereum: '/logos/chains/ethereum.png',
  fantom: '/logos/chains/fantom.png',
  hyperliquid: '/logos/chains/hyperliquid.png',
  linea: '/logos/chains/linea.png',
  mantle: '/logos/chains/mantle.png',
  optimism: '/logos/chains/optimism.png',
  polygon: '/logos/chains/polygon.png',
  scroll: '/logos/chains/scroll.png',
  solana: '/logos/chains/solana.png',
  sui: '/logos/chains/sui.png',
  tron: '/logos/chains/tron.png',
  zksync: '/logos/chains/zksync.png',
};
